[[actions]]
name = "Launch Game"
path = "thetrail.exe"
platform = "windows"

[[actions]]
name = "Launch Game"
path = "The Trail.app"
platform = "osx"

[[actions]]
name = "Launch Game"
path = "nw"
platform = "linux"